version: "3.8"

networks:
  harvestnetwork:
    external: true

services:
  harvestapp:
    container_name: harvestapp
    image: rixwand/harvest
    ports:
      - 3000:3000
    networks:
      - harvestnetwork
    environment:
      DB_HOST: 10.20.0.2
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: icwangdi
      DATABASE: harvestgrafika_db
      SECRET_KEY: bungkussupermi
